[package]
name = "dt"
version = "0.1.0"
authors = ["Vijay Kiran <mail@vijaykiran.com>"]

[dependencies]
log = "0.4.6"
chrono = "0.4.6"
#log4rs = "0.8.1"
env_logger = "0.6.0"
tera = "0.11"
clap = {version = "~2.32.0", features = ["yaml"]}
